name: dirl
channels:
  - defaults
  - conda-forge
dependencies:
  - pip==21.3.1
  - python==3.8
  - pip:
    - matplotlib==3.4.2
    - numpy==1.21.5
    - scikit-learn==1.0.2
    - scipy==1.8.0
    - torch==1.11.0